### PR TITLE
Remove tracking tools

### PR DESCRIPTION
**Pull request by Cipulot**
As per title.

### CODE REVIEW

**Comment by Cipulot** [comment]
This should address 226 and 244.

**Review by olivia — APPROVED** [review]
We should investigate something like https://docs.sentry.io/platforms/javascript/user-feedback/#crash-report-modal to not completely remove any mechanism for a user to report errors, but that’s not a blocker for this.

**Comment by Cipulot** [comment]
> We should investigate something like https://docs.sentry.io/platforms/javascript/user-feedback/#crash-report-modal to not completely remove any mechanism for a user to report errors, but that’s not a blocker for this.

I think for now removing them all together is ok, and in the meantime explore alternative methods of collection in case user wants to share info.

**Comment by Niko-O** [comment]
When can we expect this change to be in effect?

**Comment by Cipulot** [comment]
@Niko-O it should be live already. From what I recall the deploy happens as soon as GH actions in this repo are done.

**Pull request merged**
